\newpage

# Raymond Aron {#aron}

<!--
Cuadernillo pendiente de transcripción.
Cuando completes las sesiones de transcripción de Aron, el contenido va aquí,
con la misma convención de niveles de encabezado (## y ###).
-->

## Raymond Aron (1905-1983)

Intelectual de origen judío, condiscípulo de Jean Paul Sartre. Introduce y divulga en Francia la obra de filósofos como Dilthey, Husserl y Heidegger, a resultas de su interés juvenil por la filosofía alemana, y de sus estudios filosóficos desarrollados en ese país.

Escribió en periódicos y revistas abogando por la tolerancia, la democracia y el capitalismo, en una época en la que era la moda ser de izquierda revolucionaria y marxista. De hecho, al parecer su temperamento lo llevó siempre a la moderación y a la evitación de toda posición extrema. Pragmático y cortés, la rebelión de Mayo del 68 parisino lo "exasperó hasta sacarlo de sus casillas".

Remó contra la corriente ideológica por décadas, y solo cuando el derrumbe mundial del comunismo hizo girar todas las veletas en su dirección ganó el reconocimiento general. Aun así, según don Mario, no se envaneció, muy en la línea de su temperamento.

Profesor del *Collège de France*, era asimismo analista de actualidad en múltiples medios, y daba a sus escritos un ordenamiento que elevaba su trascendencia.

Aron era judío de origen pero venía de un hogar no religioso, y personalmente se consideraba agnóstico. Por ello, su judaísmo solo cobra relevancia cuando se aproxima al mundo intelectual alemán. Aun así, fue germanófilo toda su vida, y promotor de la tolerancia religiosa y de la inmigración.

Es autor del volumen *"De Gaulle, Israël et les Juifs"*, de 1968, en donde matiza el apoyo a la solución israelí y analiza sus consecuencias. Era un partidario de De Gaulle, pero como solía ser el caso, con reticencias y sin abandonar su derecho a la crítica. Es evidente que Vargas Llosa admira en Aron la independencia intelectual y el valor de exponer posiciones impopulares con sólido fundamento, como cuando admitió, mucho antes que el resto de la derecha francesa, que la Independencia de Argelia era un evento político ineludible.

Interesante saber que, en esa Francia previa a mayo del 68, incluso los progresistas pensaban que colonizar pueblos como el argelino era, a fin de cuentas, hacerles un bien, pues se consideraba que así se les salvaba del atraso cultural y de una realidad sociopolítica anacrónica (por ejemplo, Argelia era, a la sazón, una nación semifeudal).


## El Opio de los Intelectuales (1955) 

Aun más que con sus colegas nacionalistas de derecha, Aron se enfrentó con sistematicidad y resiliencia a la intelectualidad marxista y existencialista, como Merleau-Ponty, Sartre y Althusser. Centra sus críticas en ese sector, pero incluye representantes desde la misma Edad Media. 

En esta obra, critica también a los cristianos que creían que una aproximación entre cristianismo y marxismo era posible.

Con entusiasmo apostático, Vargas Llosa equipara CRISTIANISMO (?) con marxismo y con comunismo, y empaqueta bajo la misma etiqueta a este y al cristianismo, como si el símil de la ideología política como religión fuera verdad literal, sin notar en sí mismo las huellas delatoras de la afiliación liberal ferviente y cuasi religiosa que mantuvo hasta el final de su vida.

Casi por definición, la adhesión sincera a una ideología genera una actitud de irreflexión fanática, una suspensión de la capacidad crítica que solo algunos, como don Mario, matizan hasta cierto punto. Supongo que el único creyente ideológico racional es el que se convierte y se desafilia a sí mismo cada día.

Queda establecido, entonces, que *"El Opio de los Intelectuales"* se enfoca no tanto en una crítica hacia el marxismo -ya emprendida y ratificada décadas antes-, sino en la oposición razonada a los cristianos de izquierda y los existencialistas.

Aron se alinea con Albert Camus contra Sartre, quien defendía a la Unión Soviética de su época a pesar de que ya se iba sabiendo de los campos de concentración y otros horrores comunistas.

Aron denuncia, con justicia, la demoledora seducción de la violencia política sobre buena parte de la clase intelectual europea. De paso describe las agonías, hoy familiares para cualquier persona medianamente informada, del Estado soviético y sus satélites de Europa Oriental: cómo los obreros siguen siendo esclavos, en esas naciones, del Estado despótico, mientras que en el Primer Mundo -Inglaterra, Alemania, EEUU- la clase obrera goza de un estándar de vida incomparablemente superior al de sus contrapartes del tercer mundo de su época y los del siglo previo, cuando Marx escribía sus obras.

No se engañaba Aron al ironizar la paradójica posición de los intelectuales europeos y los cristianos de izquierda, que no vivían en contacto con obreros reales, los cuales tenían aspiraciones ajenas a las revolucionarias, más prosaicas y mundanas. Más bien pasa desapercibida para Vargas Llosa la contradicción de un conglomerado de intelectuales que ni era coherente con sus reclamos, ni tenía poder alguno para salvar o remediar el calamitoso estado de los países comunistas. ¿Dónde estaba, en los cincuentas, sesentas y setentas, el declarado poder de los intelectuales? ¡Ni siquiera tuvieron la capacidad, la mayoría, de diagnosticar con agudeza la condición crítica de su paradigma político, ingiriendo, con candor infantil, cada uno de los contenidos de la propaganda comunista!

Sobre la prosperidad relativa de los obreros de los países desarrollados: está claro que nunca se trató de un asunto de nivel cuantitativo de ingreso, sino de la alienación, la explotación y otros fenómenos de índole cualitativa. Por supuesto, un obrero sin conciencia alguna de clase, ante un mayor ingreso, probablemente acabe comprando un televisor o una mejor vivienda, antes que cualquier otra cosa, ¿y quién podría culparlo? Solo reacciona de manera natural a lo que llega a tener, con las ideas que su mente contiene. Nadie, o muy pocos, son revolucionarios natos o espontáneos. Inscritos en un medio ambiente consumista -el mismo que Vargas Llosa y demás liberales rechazan, con horror, regular de forma alguna-, derivarán sus excedentes hacia los productos o servicios que el mercado libre les ofrece. Ejercerán su libertad de consumir, habida cuenta de que su libertad de luchar y oponerse al modelo socioeconómico les es negada *de facto*, antes de que puedan siquiera concebirla, porque "no contribuiría a su espíritu". Aunque sí convenga -oh, dulce coincidencia- a los capitalistas que medran de ese consumismo sin alternativas.

Aron dedica un capítulo completo de *"El Opio de los Intelectuales"* a la metáfora del marxismo en tanto "religión secular", agotando el símil hasta sus últimas consecuencias: habla de ortodoxias y heterodoxias, de sectas, y hasta de "Inquisición". Es, supongo, natural en alguien de su época, obsesionado con enfocar el reflector sobre las taras comunistas, incurrir en estas artimañas retóricas. El francés no gozaba del beneficio de la evidencia histórica, que hoy revela sin ambages la inviabilidad y eventual corrupción del marxismo, tal como se practicó a lo largo del siglo pasado. En la actualidad, solo un fanático abundaría en tal exceso caricatural, porque ya no hay nada que temer ni probar.

Don Mario deplora amargamente la irreflexión francesa de los años sesenta y setenta, y reprocha a Merleau-Ponty y otros intelectuales afines haberse convertido en defensores de las barbaridades del estalinismo, incluso a sabiendas de toda su inhumanidad.

Aron coincide con Popper en su crítica a la "idolatría de la Historia" entre los marxistas, y la creencia de estos en el fin de aquella con el advenimiento de un gobierno que suprimiera la lucha de clases y el triunfo inexorable de la clase obrera.

## La Revolución Inhallable (1969)

Texto sobre mayo de 1968. Disturbios estudiantiles que se inician en la universidad de Nanterre, se extienden a la Sorbonne y, de allí, a la práctica totalidad de universidades del país. Vargas Llosa subestima su impacto, y señala que la celebridad histórica que se le ha otorgado es desproporcionada. Su mayor legado, según afirma, consiste en la liberalización sexual, la relajación de las formas tradicionales de urbanidad (o lo que pasaba por serlo, hacia la mitad del siglo XX), y la proliferación libertina de la vulgaridad y la grosería en los medios de comunicación masivos.

En efecto, se trató de una etapa de licencia cuasi anárquica, antiestalinista, durante la cual se estiraron los cánones hasta despojarlos de todo sentido. Pero estaba condenada a no dejar huella precisamente porque ejercía una lógica incompatible con la marcha cotidiana de las organizaciones. Fue un movimiento místico y absolutamente interesante, y probablemente el único ejemplo reciente, dentro del Primer Mundo contemporáneo, de quiebre organizacional, si bien momentáneo. Fue una asonada lírica, tremendamente idealista y no violenta en general, que llegó a contaminar dichosamente incluso a diversos sindicatos, y que se disolvió como la espuma de una ola cuando la ordinaria práctica del voto llevó a la ratificación del *business as usual* bajo la forma del partido de De Gaulle.

Aquí Aron apunta un hecho que quizás cabría generalizar al caso peruano: después de la ruptura idealista, el realismo pragmático de los partidos de derecha se restaura, de forma espontánea y aparentemente inevitable[^verg].

[^verg]: Ver, por ejemplo, Vergara, A. (2018). Ciudadanos sin República: De la precariedad institucional al descalabro político (2.ª ed.). Editorial Planeta.

Para resumir: en medio de la ola de la virtual integralidad de la *intelligentsia* francesa -de Sartre a Foucault- en apoyo al movimiento, el mesurado Aron condenó, en un inusitado arranque de furia conservadora disfrazada de liberalismo económico, al movimiento estudiantil. Señaló su aparente caos ideológico -que era su fortaleza y su sello-, y recomendó una elitización del estudiantado, con la finalidad de evitar la "latinoamericanización" de la universidad francesa (¡y Vargas Llosa, más que implícitamente, apoya este prejuicio!), y aumentar la calidad pedagógica y la inserción laboral posterior de los futuros egresados. Se reitera en sendos artículos y ensayos, defendiendo a la sociedad de consumo del embate de masas de jóvenes e intelectuales, cuyas únicas armas eran el debate, la pluma y las pancartas.

Admite que hay reformistas al interior de las movilizaciones, pero están opacados hasta la impotencia por las "hordas" (mi término) de maoístas y castristas. Como buen liberal, tan solo el término "revolución" o "revolucionario" parece enronchar al sensatísimo Aron.

Se equivoca don Mario, como se equivocó Raymond, al medir Mayo del 68 con la vara de los resultados concretos y medibles a nivel de la gestión universitaria. Eso sería como medir a un caballo por la cantidad de ecuaciones que puede resolver. Si bien el movimiento se inicia en las universidades como protesta ante su mala marcha, en realidad muy pronto mutó hacia una ebullición de propuestas, incompatibles con la lógica corporativa organizacional, y por supuesto naufragó al estar inscrita en una sociedad planteada en tales términos.

Una y otra vez, Aron reivindica "su" modelo de sociedad consumista porque en ella no se halla a los déspotas del pasado, los que gobernaban a hierro y fuego, los que aplastaban la resistencia y oprimían a los disidentes. Pero no ve la tiranía del comunismo, la ubicuidad opresiva de la mercancía, y la falta de alternativas que caracterizan al capitalismo desbocado. Confunde los billetes con la autonomía, y la dictadura penumbrosa de los magnates le parece la más pura libertad, porque ya no hay nadie que te dictamine qué puedes pensar, pues lo importante es que te digan lo que tienes que comprar y lo hagas.

En esos años aún no se entreveía la prepotencia engreída de los multibillonarios que compran territorios para crear enclaves independientes[^thiel], que echan por tierra el derecho internacional porque es malo para los negocios, y que confunden decencia con falta de soberanía. Su horizonte no permitiría entrever la destrucción climática y la depredación irreversible. Todo lo que veía era la ausencia de tiranuelos concretos, y era ciego a la imposición mercadológica, y a la domesticación del método científico para darle la forma de tecnología que transmuta al investigador en mercachifle.

[^thiel]: Srinivasan, B. S. (2022). The network state: How to start a new country. https://thenetworkstate.com/Srinivasan

Se puede ser indulgente con Aron, porque escribía entre el fin de los sesenta e inicios de los setenta. Pero ¿quién absolverá a los liberales que, viendo todos estos males hoy planetarios e irreversibles ya, siguen apoyando al capitalismo?

"No hay incompatibilidad entre las libertades políticas y la riqueza", sostiene don Mario. Supongo que, ejercidas en un plano general y simbólico, las libertades políticas no colisionan con la riqueza, en contextos muy específicos (y, en mi opinión, bajo consideraciones algo más que miopes). Pero la evolución del capitalismo en los años recientes nos demuestra que, más allá de un nivel local dentro de un puñado de países altamente homogéneos, con una historia política y cultural muy rica, las libertades políticas son restringidas y anuladas por el poder económico, cuando este es trasladado sin mayor procesamiento a la arena política.

Según el diagnóstico del autor peruano, esa feliz conjunción de riqueza y libertad política, florecida en el jardín de la economía libre, tiene como enemigo fundamental al Estado. Fijo en una era thatcheriana y reaganesca, don Mario parece convencido que esa es la amenaza a vencer, pues el Estado es "constitutivamente voraz".

La ironía es que el liberalismo exuda su propia interpretación de la Historia, a pesar del enfoque popperiano. Y esa interpretación ha sido desmentida por la última década de devenir político.

La segunda gran ironía es que, si bien es cierto que el ser humano se equivoca casi siempre extrapolando su interpretación histórica hacia su propio futuro, tal extrapolación es absolutamente inescapable y consustancial al entendimiento del pasado.

Así como Aron caricaturizaba al marxismo, asimilándolo a las categorías religiosas, un ejercicio paralelo podría emprenderse en relación al liberalismo. En ese contexto, Vargas Llosa sería un elocuente predicador, embebido del clásico furor del apóstata, presto a satanizar a los enemigos de la Fe, los "marxistas infieles", y el "Estado voraz", como los cristianos medievales anatematizaban a los árabes y al "mundo", como oposición conceptual de la Iglesia. Teme al "salto de cangrejo" histórico, que nos devuelva -mejor dicho, que devuelva al Occidente del Primer Mundo- al "oscurantismo". ¡Como si algo así fuera posible! Además afirma que ese oscurantismo "pervive en buena parte del planeta". Asumo que se refiere al mundo subdesarrollado, ignorando el sencillo hecho de que tal subdesarrollo es fomentado y mantenido, en parte, por la dinámica capitalista, devenida imperialista en la arena internacional. 

A la luz del trumpismo, queda ya claro que el Occidente desarrollado mismo transitará en pleno -como ya lo ha hecho EEUU- a la total transgresión del Derecho y el Orden Internacionales, regresando a su añeja predilección por la dinámica imperialista. Con esto en mente, cabe cuestionarse: ¿Quién ha terminado dando el "salto del cangrejo"? ¿Quiénes han retrotraído al mundo a lo que era antes de la Segunda Guerra? ¿Quién hunde a sus poblaciones en un segundo oscurantismo, donde reina el *brainrot* de las redes y la educación de calidad es reservada para las élites?

Para Aron, la neutralidad en política no puede existir. Esto, evidentemente, es cierto en el sentido en que todo acto ejecutado en la arena política tendrá un significado y una repercusión política. Lo cual no es lo mismo que decir que no pueden existir posiciones ideológicas equidistantes de cualquiera de los polos políticos.

Sartre y Aron tienen una relación casi vitalicia, y carreras paralelas. Se convierten -al menos en la óptica de don Mario- en las luminarias más espectaculares del panorama intelectual francés de su época.

## Luminarias opuestas

Sartre, celebérrimo hace algo más de seis décadas, viene conociendo una posteridad anémica, huérfana casi por completo de discípulos o de influencia reconocible entre los autores contemporáneos. Fue un alumno brillante, al mismo nivel inicial que Aron, aunque prematuramente marcado por su fealdad[^feo]. Se propuso ser un filósofo y un literato destacado, en paralelo, y lo logró.

[^feo]: Por lo general, asignar este tipo de etiquetas se consideraría por lo menos subjetivo y de mal gusto, pero el peruano alude más al impacto de la autopercepción en Sartre, y a su reelaboración deliberada. Recordemos que, más allá de lo estético, para el autor de *Huis Clos* la fealdad como producto de la "mirada de los otros" llegó a sublimarse hasta convertirse en categoría filosófica ---*être-pour-autrui*--- y, ya en una dimensión más cotidiana y de estilo de vida, un poderoso móvil que lo llevó a lo que Alfred Adler llamaría *sobrecompensación* (Adler, A. (1965). El carácter neurótico. Paidós), volviéndose un mujeriego empedernido.

Excepcional en muchos sentidos, en la posguerra francesa llegó a ser tan famoso como Juliette Gréco y Edith Piaf; el lanzamiento de sus libros y el estreno de sus dramas convocaban multitudes. Tuvo una sonada controversia con Albert Camus acerca de los campos de concentración de la Unión Soviética (el argelino en contra; él a favor).

Don Mario rememora las inacabables tardes y noches que en su juventud le dedicara a la lectura de Jean-Paul -por esas épocas llegarían a apodarlo *"El Sartrecillo Valiente"*, según él mismo ha relatado muchas veces-; pero para el momento de elaborar la obra que nos ocupa solo lo tiene presente de una manera a la vez emocionalmente distante y cognitivamente actual, como una mujer recuerda a un exnovio, digamos, al que en su momento quiso mucho pero por el cual, décadas mediante, no solo es incapaz de volver a sentir afecto alguno, sino de siquiera entender a ese yo suyo del pasado, que abrazara tan torpe infatuación. Sin duda, la justificación que hizo Sartre de los *gulags* soviéticos está entre las más perennes manchas en las que haya incurrido un intelectual occidental de su rango, y ha dañado la perduración de la que hubiera podido gozar.

Aun así, las efemérides de ambos filósofos[^efe], incluso tantos años luego de su desaparición, siguen favoreciendo al autor de *"El Ser y la Nada"* por sobre la figura de Aron. Se diría que el recato y la vocación de desdén por el aplauso de las mayorías han seguido a Raymond más allá de la tumba.

[^efe]: Esto es, el ceremonial organizado por las instituciones oficiales del Estado francés conmemorando a ambos personajes.

Lo contrario sucedería con sus obras, según don Mario: mientras que la de Aron se habría mantenido vital tras su muerte, la de Sartre languidece en todos los frentes, sobre todo los dramas y las novelas.

Con estas observaciones llama entonces algo la atención que Vargas Llosa insista en que, de forma póstuma, Sartre acapare todavía más atención que su antiguo condiscípulo. Para él, la razón hay que achacarla al carácter espectacular -en el sentido de Guy Debord[^espec]- que ha adquirido la cultura: el opaco Aron no ofrece el mismo potencial, en este sentido, que Sartre, a pesar de -o precisamente por- sus posiciones políticas chirriantes.

[^espec]: Debord, G. (2002). La sociedad del espectáculo (J. L. Pardo, trad.; 2.ª ed. rev.). Pre-Textos. (Obra original publicada en 1967)

En este ámbito, me atrevo a lanzar una sugerencia: el carácter "espectacular" de la cultura contemporánea masificada, que premia el histrionismo y lo llamativo formal, por sobre la contundencia del fondo y el valor intrínseco del personaje y su obra, responde a un mecanismo de psicología colectiva, y no de la cultura ni de las obras en sí mismas. Es la mirada y el cristal con que se mira lo que trivializa las propuestas y recompensa la superficialidad, precisamente porque estamos hablando de una consideración o actitud agregada y una acción o consecuencia masivas.

Una vez más, el escritor peruano retoma el ímpetu apostático, y de haber sido un acérrimo sartreano pasa, tras las décadas y la inversión de sus simpatías, a sugerir que Sartre fue, si no un "colaboracionista" durante la ocupación alemana, al menos un resistente más bien contemporizador y gestual, bastante tibio comparado con quienes sí fueron miembros efectivos de la resistencia, como André Malraux y Albert Camus[^inq].

[^inq]: Uno diría que pocos antagonismos son más fieros que la inquina de un converso contra su antigua fe.

Don Mario dice que el viejo Jean Paul se volvió más extremo en sus posturas políticas como una forma de conjurar y contravenir la ambigüedad de su posición durante la Guerra. No se percata de que algo similar podría decirse de él mismo: su fanatismo liberal podría entenderse como un modo de compensar sus viejas filias comunistas.

Cerrando la sección correspondiente a Aron, Vargas Llosa nos dice que muchos de los eventos de la actualidad le dieron la razón, pero no todos. Los obreros franceses han pasado a votar por Le Pen, pero el por entonces joven Macron, de centroderecha, logró imponerse electoralmente, y la intelectualidad francesa actual está bien lejos de la izquierda.

Tal vez, en coherencia con el esquema popperiano, uno no debería esperar y mucho menos medir el legado de un intelectual por su capacidad de anticiparse a un futuro histórico supuestamente inaprensible.
