# Jean-François Revel {#revel}

<!--
Cuadernillo pendiente de transcripción.
Cuando completes las sesiones de transcripción de Revel, el contenido va aquí,
con la misma convención de niveles de encabezado (## y ###).
-->
## Jean-François Revel (1924-2006)

Vargas Llosa descarta con desparpajo a los "nuevos filósofos" franceses, destacando, en cambio, a Jean-François Revel en la arena intelectual.

Se trató de un periodista y ensayista capaz de distinguir los usos retóricos útiles de aquellos que se alejan peligrosamente de la realidad práctica. Para el peruano es comparable a Camus y a George Orwell para la época contemporánea. Fue socialista, pero su objetividad le granjeó siempre críticas y antipatías, no solo de quienes estaban en puntos lejanos del espectro político, sino también de sus partidarios.

Así pues, se distinguió por su "retorno a los hechos", y por el uso de ellos en cuanto criterio para evaluar la validez de las teorías y doctrinas políticas. Sin duda, muchos de los adherentes a la izquierda suelen incurrir en ese pecado capital que consiste en interpretar, a la luz ideológica, cada hecho considerado, hasta llegar al punto de desnaturalizarlo. En el Perú hemos tenido, por ejemplo, a líderes de izquierda incapaces de caracterizar a regímenes como el chavismo venezolano como lo que son: tiranías indefendibles, en contra de cualquier concepción de decencia no solo política, sino humana.

Claro está, esta especie de laboriosa distorsión no está reservada a progresistas y socialistas, si bien estos parecen más culpables por el contraste que sus posiciones adquieren contra el panorama general del capitalismo liberal hegemónico. Hoy parecería sinónimo de sensatez y de sentido común sostener que la única manera civilizada de vivir es la democracia liberal y capitalista, olvidando la injusticia y desigualdad crónicas que esta permite, la relegación de las inmensas mayorías por diseño, el timo cotidiano de vender distracciones para compensar por la intolerancia política y la subordinación irreversible. Todo eso aun asumiendo que se vive en una sociedad que cumple con todos los prerrequisitos institucionales e ideológicos para tildarse a sí misma de "democrática", caso sin duda ajeno a la sociedad peruana en lo que va de este siglo[^nomdem].

[^nomdem]: En lo formal el Perú es una democracia, pero casi todos los componentes funcionales de esta (las garantías constitucionales, el voto mismo, el orden jurídico, cada una de sus instituciones tutelares y el contrabalance entre estas, y por supuesto los valores democráticos) han sido violados en algún momento, y muchas permanecen en tal estado degradado. Como bien estableció Levitsky (Levitsky, S., & Ziblatt, D. (2018). How democracies die (F. Sanders, narr.) [Audiolibro]. Random House Audio. https://www.audible.com/pd/B078KQ9VDW), desde hace algunas décadas las democracias ya no mueren espectacularmente, precedidas de estrépito, crímenes y tanquetas, sino bajo insidia, tras meses o años de medidas y prácticas autoritarias inoculadas paso a paso. Estas "democracias zombie", guardan muchas de las apariencias, pero evidencian la índole antidemocrática en cuanto se las analiza con cierto cuidado. 

Don Mario, de paso, intenta contrabandear, dentro de su justa crítica de la ideologización distorsionadora, la idea de que la única vía de la verdad epistémica va de lo concreto de los hechos a lo general de las teorías. Una noción que cualquiera, luego de breve reflexión, debería complementar con la siguiente añadidura: *lo que permite interpretar la realidad y los "hechos" es una teoría funcional*. Las hay de todo tipo y calibre, desde las meramente idiosincrásicas hasta las abiertamente racionalizadas, pasando por las triviales y de lugar común (que la gran mayoría utiliza casi todo el tiempo). Lo que no hay, ni puede existir, es un individuo absorbiendo hechos sin ningún modelo mental general y previo, que permita clasificar, entender, evaluar y eventualmente predecir esa realidad.

Sucede que la mayoría de personas acaba enamorándose de sus propias teorías, y confundiendo los "hechos" con su interpretación de ellos, "aplanando" el proceso epistémico para así, por conveniencia y comodidad, establecer una falsa equivalencia entre los estímulos del mundo y su percepción de ellos, entre lo que se ve y lo que se piensa de lo que se ve.

Lo que sucede, casi siempre, es que hay teorías que nos permiten predecir, o al menos describir, los hechos de forma tal, que todos o casi todos los miembros de nuestra comunidad de referencia acaban por concluir más o menos las mismas ideas al respecto. Y es entonces que pensamos, no sin cierta razón, que estamos percibiendo la realidad de manera objetiva y sin sesgos. Hasta que alguien —o algunos— logran generar un entendimiento más profundo, lo cual nos lleva a comprender que nuestra percepción no es exacta ni mero espejo del "hecho tal cual es".

Esto es válido para absolutamente todos los procesos de enfrentamiento a la realidad, desde la simple percepción de una flor —que para nosotros tiene un color, pero para los insectos polinizadores otro, echando por tierra la noción de "visión de las cosas tal cual son"— hasta nuestra interpretación de la muerte de un manifestante en una vía pública a manos de un policía, quien puede ser considerado un asesino o un "héroe de la democracia", según nuestro sistema ideológico. En este último caso, es patente que lo importante no es el "hecho" del ser humano fallecido —con todo lo monstruoso que pueda sonar— sino *cómo nos sentimos y qué debemos hacer al respecto*. Lo cual desemboca en la vieja primacía de la ideología por sobre los hechos: no somos videocámaras ni espejos, no podríamos serlo nunca. En cuanto seres vivos y humanos, estamos construidos de tal forma, que debemos interpretar, reaccionar y prever lo que sucede en el mundo, y esa interpretación, reacción y previsión es en lo que consiste estar vivo y ser consciente.

Ninguna de esas tres funciones nos es revelada por los hechos en sí, si acaso algo como los hechos descarnados realmente es relevante.

## ¿Para qué los Filósofos?

Revel era un marsellés excepcionalmente logrado en todos los ámbitos educativos. Fue docente de filosofía en México y Florencia, y miembro de la resistencia durante la ocupación. Su primer libro fue *"¿Para qué los Filósofos?"*, aunque antes había publicado una novela que jamás reivindicó.

En esa primera "obra seria" se encarniza con Heidegger, con Lacan, con Lévi-Strauss, que en ese momento aún no eran las vacas sagradas de la intelectualidad en que se convertirían algún tiempo después.

Ese libro fue una quema de sus naves filosóficas. Luego de su publicación, se autoexilió de la Academia, en especial de las universidades francesas y del abordaje que en ellas se hacía de las Humanidades.

Empezó una carrera brillante como periodista y analista político. Vargas Llosa aprecia en él —y en Aron, a quien analizamos ya— su pertinacia intelectual, que los haría perseverar en sus escritos incluso cuando la época se decidía por favorecer al marxismo.

Como editor, publicaría una colección de panfletos clásicos, material escrito por gigantes como Voltaire, Diderot, Hume y otros, que demuestra que en aquellos tiempos el oficio panfletario no era en absoluto despreciable. Ese fue también el reino de sus propias obras, y el estilo en el que se sintió más cómodo.

En su primer libro lanza justificadas críticas al quehacer filosófico de su tiempo, su ilegibilidad para el *dilettante*, su desvío al parecer irreversible hacia los territorios de la Lingüística, y su desconexión con toda aplicación práctica. A esa Filosofía la rechazaba en pro de, por ejemplo, los gigantes griegos de la Filosofía Clásica, a quienes estudió a profundidad.

Revel rescata, sin embargo, a Sartre, y también a Freud, a quien reivindica tanto como despreciaba a Lacan, quien a su juicio solo había distorsionado a Freud a fin de ganar para sí mismo una inmerecida consideración.

Por otro lado, Vargas Llosa considera no del todo justas las críticas de Revel acerca de la obra de Lévi-Strauss, a quien acusa de ser mejor psicólogo que antropólogo o sociólogo. Lo cierto es que, al momento de redactar su primer libro, Revel no podía haber tenido una visión completa de ella, ya que el gran antropólogo aún no la había completado para entonces. Pese a ello, en el prólogo de la segunda edición de *"¿Para qué los Filósofos?"* no rectifica nada y más bien reitera su posición y la extiende al conjunto del estructuralismo, en especial contra Althusser y Foucault.

Definitivamente, hay que ser poco menos que un profesional para aprehender y evaluar la obra filosófica de los estructuralistas y post estructuralistas, pero ello, por un lado, nada nos dice que la validez intrínseca de sus propuestas, y por el otro, nos hace aparecer como críticos superficiales renegando de características formales antes que de cuestiones de fondo.

Roland Barthes expresa uno de los pináculos de esta tendencia al "esoterismo filosófico", con su entrecruce de la Filosofía con la Lingüística.

Dentro de la línea planteada por Raymond Aron, Revel trata siempre de escribir de forma clara sin por ello descuidar el rigor intelectual. Se trata en ambos casos de francotiradores filosóficos, apuntando a los filósofos marxistas o marxistoides, empecinados nadadores contracorriente. Fue, según el escritor peruano, transparente sin ser superficial, un logro en sí mismo, tanto en sus libros como en sus numerosos artículos.

Pese a los señalamientos —más o menos arteros— de sus compañeros de tendencia política, Revel nunca fue un conservador. Fue un socialista partidario, candidato a diputado por el partido de Mitterrand, y un acérrimo anticlerical.

Imposible ser conservador cuando inscribe uno, al inicio de un memorias, una frase como esta: "aborrezco a la familia, tanto aquella en la que nací como las que yo mismo fundé."

## La Tentación Totalitaria (1976)

En esta obra Revel afirmaba que el mayor obstáculo para el triunfo del socialismo no era, como pudiera pensarse, el capitalismo, sino el marxismo.

Proponía a la socialdemocracia como una opción de sistema político, capaz tanto de fomentar el desarrollo económico como la tolerancia como valor social.

Vargas Llosa señala que este libro fue publicado al tiempo que en el Perú se padecía el régimen dictatorial de Juan Velasco Alvarado, al que los cuadros de izquierda calificaban de "progresista". La verdad es que para cuando Revel publicaba este volumen, ya el régimen velasquista había terminado y se establecía una dictadura mucho más conservadora, con el General Morales-Bermúdez a la cabeza. Aun así, queda evidente la deriva autoritaria del general piurano, que acabaría por desnaturalizar al menos algunos de los cambios sociales más señeros en nuestra sociedad[^jva].

[^jva]: Sea que se lo ame o se lo odie, el Perú de hoy es incomprensible sin las reformas del velasquismo; tan incomprensible como la supervivencia de las muchas taras pseudomedievales que el piurano encontró a su llegada al poder, y que desterró a las mazmorras más oscuras de nuestro pasado nacional. Tan incomprensible como la nostalgia de ciertos peruanos añejos por el *Ancien Régime* de los latifundios y las mineras que actuaban con prepotencia feudal. 

Más allá de Revel, habría que cuestionarse por qué, pese a las sucesiones democráticas previas y posteriores, tuvo que apelarse a un régimen autoritario para realizar algunos de los cambios sociales más rotundos, giros en la cultura gubernamental que no pudieron concretarse con un presidente democráticamente elegido.

## Ni Marx, ni Jesús (1970) 

Aquí Revel sostiene que los grandes momentos de rebeldía no se han producido como el antecedente de los cambios de régimen en los países gobernados por el comunismo, sino en el corazón de las sociedades capitalistas, como Gran Bretaña y los Estados Unidos. Afirma que son los estudiantes, las mujeres, y los miembros de las minorías quienes, en la práctica, cuestionan y se rebelan contra las ideas y las instituciones más acendradas, mientras que en las sociedades supuestamente gobernadas por los valores de justicia y equidad —pero que carecen de ellas— no es ya ni siquiera posible rebelarse.

Asimismo, argumenta que la ausencia de una posibilidad real de crítica deteriora la estructura de una nación, entregándola a la corrupción y al estancamiento, y que esa era, de entre todas, la más poderosa raíz de la decrepitud y caída de las naciones comunistas. La censura sería, así, el inicio del fin de todo régimen político.

*"Todo poder es, o se vuelve, de derecha; solo lo convierte en izquierda el control que se ejerce sobre aquel, y sin libertad, no hay control"*, escribiría.

## Cómo terminan las democracias (1983)

Segundo en nombradía y prestigio (solo detrás de *"La Tentación Totalitaria"*) es *"Cómo terminan las democracias"*. Se trata de una obra apocalíptica, que vaticina la caída del sistema y los valores democráticos, que terminarán, según Revel, por convertirse en una especie de nota al pie de la Historia, un paréntesis de civilización irrepetible, una utopía condenada a perderse[^ffk].

[^ffk]: Cabría un análisis comparado con *"El Fin de la Historia"*, de Fukuyama, que sostiene la tesis opuesta.

La propuesta central de la obra es que el comunismo soviético emergía de la Guerra Fría victorioso[^coldwar] en dimensiones múltiples, desde la psicológica a la política, en buena parte gracias al autosaboteo irresponsable de las mismas democracias, podridas desde su propio interior. Según las extrapolaciones de Revel, una vez que un país caía dentro de la influencia de la URSS, el Occidente Democrático asumía la derrota como definitiva, y facilitaba en la práctica el trabajo del comunismo internacional.

[^coldwar]: Resulta algo misterioso que MVLL, quien supuestamente redactaba este libro entre 2015 y 2017, y por lo tanto estaba perfectamente claro acerca de la caída del Muro de Berlín y el nuevo orden al que dio lugar, insistiera en siquiera mencionar una obra cuya premisa fue tan radicalmente desmentida por la realidad. 

Por alguna razón, Vargas Llosa considera esta obra, cuyo corazón es una profecía fallida y tremendista, como una de los mejores de Revel.

El peruano hace eco de la múltiple denuncia elaborada en su libro por el francés, enumerando la multitud de iniciativas de todo tipo mediante las cuales la URSS fomentaba la expansión de su influencia a nivel mundial, y la contrasta con los movimientos en pro del desarme unilateral en Occidente.

Escrito antes de las épocas del intervencionismo renacido con el segundo gobierno de Trump, y víctima de la miopía ideológica que le impedía percibir el entretejido de sanciones, presión diplomática y simple *bullying* económico de los EEUU en el continente americano, Revel es un ejemplo de los peligros implícitos en el periodismo político: a saber, la tentación, casi siempre irresistible, de formular generalizaciones y juicios permanentes de valor gatillados por acciones coyunturales y escenarios geopolíticos inestables.

Lo que sí es duradero y valioso en la claridad con la que Revel plantea el dilema, aparentemente insoluble, de la democracia: mantener su espíritu y sus valores de tolerancia y apertura (y ser víctima de sus enemigos, que aprovecharán esos frentes para sembrar la disidencia, la crítica destructiva y el quintacolumnismo), o por el contrario, endurecer sus métodos, cerrarse a los cuestionamientos, y perder así su esencia, acabando por metamorfosearse, en todo o parte, en aquello de lo que se quiere defender: una sociedad cerrada y autoritaria.

Habitante de un tiempo más feliz para él, uno donde los EEUU y Europa ostentaban una superioridad económica, tecnológica y científica sin rivales serios del lado del antiguo bloque soviético, Vargas Llosa asume que tal ventaja es una característica secretada por el sistema político mismo, y no un resultado directo de un mercado libre que puede ser cultivado, por una especie de hidroponía económica, incluso en el marco de países socialistas como China.

De hecho, la emergencia de China como potencia mundial, hoy incontrovertible, es una prueba de que el libre mercado es solo un mecanismo eficiente, que es posible implementar dentro de un sistema no democrático en el sentido liberal. Esto socava la base de gran parte del liberalismo económico y el puente argumental para buena parte de sus ideas y de su propuesta ideológica. Demuestra que, al fin y al cabo, al capitalismo no le interesa mucho cuál sea el marco ideológico de base, siempre y cuando le dejen las manos libres para interoperar transacciones entre agentes económicos.

Don Mario encuentra en el testimonio de los antiguos disidentes de los países soviéticos un motivo para la esperanza: ese "amor a la libertad" que él estaba seguro de percibir en los desesperados intentos de escape, tanto como en las declaraciones de quienes lograban, luego de mil peripecias, insertarse en la dinámica social capitalista. Pero en el fondo, más que "amor a la libertad" se trataba, antes que nada, de miedo a la pobreza, entendida como la privación de los productos y servicios básicos, agravada por la permanente propaganda capitalista. Ya en segundo (y distante) lugar se hallaba también el odio al tedio, la grisura y la falta de emulación de la vida en los países socialistas de entonces. 

Bien sabido es, según nos enseña la historia reciente, que las personas son capaces de sobrellevar las más pesadas cargas, perseverar en la alienación más rotunda, si a cambio se les da acceso —limitado, pero posible— a los suficientes distractores. El aforismo de Juvenal acerca del "pan y circo" sigue aplicando, diecinueve siglos después. No digo que el amor a la libertad no haya sido un móvil, pero este es un elemento específico de aquellos que *requieren de tal libertad*, y la definen en términos tales que pueda coincidir con lo que la sociedad capitalista podía ofrecer, lo cual es solo un fragmento de todas las formas posibles de entender la libertad.

La muerte de titanes previos, como Sartre y Aron, convirtió a Revel en una especie de adalid intelectual, que, voluntariamente o no, tendía a definir la agenda de la discusión política entre la "clase pensante" de su Francia natal. Sin embargo, tenía un carácter diferencial en su influencia: no era tan abstruso o elitista como otros paladines previos de las ideas, y andaba siempre más cerca del evento coyuntural que de la discusión abstracta.

## La Connaissance Inutile

El ataque a las figuras referenciales de su tiempo, que lo había acompañado desde el principio de su andadura como escritor, renacería con fuerza en su libro *"La Connaissance Inutile"*.

En esa obra también lanzaría una idea clave: que quienes lideraban la vida colectiva en incluso las sociedades de mayor educación y mayor logro científico, seguían tomando decisiones y asumiendo derroteros guiándose por prejuicios, sesgos y otras derivaciones irracionales y distorsionadoras.

Uno diría que hablaba de la clase política, de los *"decision makers"* de los países del primer mundo. Pues no: hablaba de los grandes intelectuales, quienes criticaban las libertades democráticas y ensalzaban aún los avances reivindicativos de los "países progresistas" del tercer mundo y de la órbita soviética.

Fiel a su tendencia natural, vemos pues que Revel, antes que a ideas o nociones generales, reaccionaba a la irritación del momento, si bien con cierta justicia. Muchos intelectuales reivindicaban prácticas e ideas que, de aplicarse también en sus civilizados países, los habrían arruinado o empobrecido.

En suma, Revel evaluaba el mundo previo a la caída del Muro de Berlín, y lo grandioso es que diagnosticó que el llamado "Mundo Libre" estaba en definitiva perdiendo la batalla ideológica, y eventualmente podría perder también la militar. Una vez más, un pronóstico dramáticamente fallido, que —en una ironía de segundo orden— podría usarse como ejemplo de lo que Popper criticaba con el nombre de "historicismo".

Revel criticaba a quienes, desde el Occidente desarrollado y rico, promovían lo que él llamaba "regímenes progresistas", apropiándose del término de forma más bien simplista, acusando a tales intelectuales de desinformar, mientras que, al mismo tiempo, y con los lentes del prejuicio bien puestos, decía que la pobreza de las naciones tercermundistas no se debía a clases dirigentes corruptas, estados que apenas funcionaban por potenciar el clientelismo interno y externo, o a la injerencia extranjera buscando cancelar y ocluir toda vía hacia la prosperidad de países que era más conveniente preservar en el atraso. Nada de ello. Para Revel, el culpable era el colectivismo nativo, los partidos únicos y el control de la información y la economía por el Estado; confundía los síntomas con la enfermedad y, una vez más, fallaba proclamando recetas políticas *ex-nihilo*, como si estas pudieran aplicarse desde una tabla rasa.

Las acusaciones de Revel eran tanto más efectistas cuanto que el blanco eran no solo los intelectuales de izquierda o progresistas de Europa y América del Norte, sino también los grandes medios masivos de comunicación, precisamente en la época en que estos habían alcanzado el pináculo de su influencia, justo antes de que la revolución de las redes sociales fagocitara sus audiencias y los despojara, para efectos prácticos, de buena parte de su prestigio como fuentes de información. Hablamos de instituciones como el *New York Times, Der Spiegel, Le Monde*, o *The Guardian*.

Como bien anota don Mario, si esos grandes "monstruos" del periodismo eran desde ya culpables de distorsión —según Revel—, entonces ¿qué podía esperarse de los medios oficialmente establecidos de los propios países en desarrollo? Sin duda la disolución de toda objetividad y la inaccesibilidad de la información; los hechos en una sociedad enferma de cerrazón desaparecen para la mirada pública, y como esa mirada social y colectiva es la única que los consagra como reales —del mismo modo en que un árbol en medio del bosque solo hace ruido al caer si hay alguien para escucharlo—, la verdad se disuelve y se pierde para siempre. 

Esto es certísimo e inobjetable, y en el Perú —ironía de tercer orden— se ha producido, no por obra de los medios de izquierda o "progresistas", sino precisamente por la acción corrosiva y fanática de medios liberales y conservadores, empecinados en desvirtuar una agenda que, cabe argumentar, jamás ha sido ejercida (o siquiera entendida) propiamente en el país, y que por lo tanto es tanto más temida cuanto que no se le ha visto nunca en acción, como los fantasmas.

Fue la ejecución del mal periodismo y la desinformación crónica lo que —ironía de cuarto orden— hizo que el mismo Vargas Llosa, en su ancianidad, acabara persuadido de que, para los votantes peruanos, los candidaturas de organizaciones pseudomafiosas como el fujimorismo era la única aceptable. Partido que empezó su andadura, no lo olvidemos, engañando al Perú, clamando que no ejecutaría el célebre "shock" económico que justamente Vargas Llosa, como candidato, había diagnosticado como ineludible, y que solo pudo ganarle a este esa elección mintiendo, se convirtió, como fruto de la desinformación sistemática y constante, en la única elección válida para la misma persona que se había visto derrotada por sus vilezas y sus mentiras.

Si esta no es una de las más grandes y sardónicas morisquetas del Destino, no sé qué lo sea.

\dinkus 

Un poco innecesariamente, Revel apunta que los peligros de la distorsión ideológica se extienden a la práctica científica. De eso poca duda puede haber, y la menor solidez epistemológica hace que ciertas ramas específicas, como las de las Ciencias Sociales, sean peculiarmente proclives a ello, máxime cuando el científico social se halla inscrito en una realidad tan extrema y políticamente distorsionada, que es casi imposible tocarla, incluso desde la más aséptica de las herramientas analíticas, sin contaminarse uno también. Como el caricaturizado científico de Jonathan Swift[^swift], que a fuer de estudiar los componentes elementales de la mierda termina embadurnado en ella, el estudioso de las ciencias sociales aparece contaminado y maloliente, y gradualmente le resulta más y más difícil limpiarse.

[^swift]: Swift, J. (1965). Viajes de Gulliver (R. M. Spartal, trad.). Editorial Ramón Sopena

Sin embargo, no debemos confundirnos. De lo que Revel habla no es de los inherentes peligros que acechan a quien se dedica a investigar temas espinosos y polémicos, sino del riesgo ideológico de quien distorsiona todo tipo de temas para perjudicar a sus contrincantes, concretamente a aquellos que, como los demás filósofos materia del libro, y los países del Occidente desarrollado, se oponen al "comunismo". Como ejemplo, Vargas Llosa cita a ciertos investigadores que trataron de atribuir el origen del SIDA al Pentágono norteamericano, "motivados" por manipulaciones de la KGB.

Para Revel el Occidente desarrollado era el culmen indiscutible de la Civilización, y la desidia, negligencia, ideologización dogmática y prejuicio de los intelectuales y los grandes medios de comunicación, que según él le hacían el juego al "comunismo soviético", serían los culpables de una eventual caída de la democracia occidental.

Revel era un gran prosista y sin duda un admirador del Occidente primermundista, el medio ambiente cultural en el que Vargas Llosa pasó la mayor parte de su vida; era también, sobre todo, un liberal, alguien que creía, como el escritor peruano, en la libertad como el valor supremo al cual era lícito sacrificar todos los demás. Pero también fue un historicista, en el sentido de creer que la tendencia que él creyó identificar en su coyuntura proyectaba una victoria final del temido comunismo, justamente cuando este estaba por colapsar bajo el peso de sus propias fallas internas.

La única explicación en que el peruano rendía tal admiración y predilección por Revel, y fue este tan importante para él, que no pudo obviarlo como sí que obvia la mención de sus limitaciones como intérprete de su propio tiempo.

Como ya vimos, el narrador peruano tiene una idea exagerada del poder de los intelectuales, y probablemente esa distorsión proviene de Revel, con su fallido diagnóstico de la inminente derrota ideológica de Occidente debido a la izquierdización de sus intelectuales y de algunos de sus principales medios de comunicación. Ya hemos hablando en secciones previas de este estudio acerca de por qué consideramos esta inflada concepción de los intelectuales como una especie de delusión voluntariosa; solo agregaremos aquí que quizás algo de esa imagen aumentada deba su distorsión a la brillantez de su propia biografía, a su palmarés pletórico de éxitos y reconocimientos, que lo persuadió de que la existencia de un intelectual tiene un peso social que en realidad no posee.

Es humano generalizar la vivencia propia, y transmutar la anécdota personal en principio generalizable.

Revel denunciaba que el siglo XX había puesto la libertad al servicio de la tiranía; que la igualdad había sido puesta forzosamente de rodillas ante el privilegio, y todas las propuestas de la izquierda subordinadas a la servidumbre. Es evidente, sin embargo, para quienquiera que no esté enamorado, casado y comprometido con el Occidente y su libre mercado voraz, que si la idea de la libertad se ha convertido en tiranía es, precisamente, en los países desarrollados, y no en manos ni por obra de intelectuales fanáticos del Che Guevara o Mao, sino a resultas de la codicia infinita de las grandes corporaciones y de los hiperbillonarios capaces de distorsionar no solo las reglas de juego social de las naciones en que operan, sino además de generar sus propios Estados[^thiel2]. No, el marxismo no ha sido el único demiurgo del mundo en el siglo XX y lo que va del XXI. Muerto y enterrado, ha cedido su lugar a un capitalismo sin alternativas, una quimera bifronte con una faz conservadora y otra liberal, motivadas y coordinadas por la ambición corporativa sin fronteras.

[^thiel2]: Cf. nota previa.

Ya enteramente convertido en europeísta y occidentalista de polendas, don Mario desprecia a los "países incultos" que no son ni Estados Unidos ni ninguna de las clásicas naciones europeas de vanguardia (Inglaterra, Francia, Alemania...), donde los intelectuales casi siempre son de izquierda o progresistas, "porque es la única manera de escalar posiciones en el medio cultural". Incluso llega a acusar a los intelectuales del Tercer Mundo de medrar, parasitando de las becas y de los Premios Internacionales (curiosa crítica de parte de alguien que ganó prácticamente todos los premios literarios en existencia). Es de suponer que la posición de un intelectual políticamente válido, según don Mario, de por ejemplo nuestro común Perú, debería haber sido la defensa del liberalismo político y económico, y la promoción de un Estado aún más minúsculo y anémico que el que apenas tenemos (y que ni siquiera llega a establecer su fantasmal existencia en todo el territorio nacional): No debería, ese intelectual ideal e hipotético, buscar la reivindicación de quienes han sido desfavorecidos por centurias, tratados como ciudadanos de segunda o incluso subhumanos, sino reclamado para ellos la libertad de ser lo que quisieran —que, en términos prácticos, sería seguir siendo pobres, incultos y rezagados—.

No sorprende que, a raíz de su investigación del espantoso crimen de Uchuraccay, el mismo Vargas Llosa no dejara de manifestar su perplejidad por el conato de violencia del que en algún momento estuvo a punto de ser víctima: *"¿De dónde nace esa violencia? ¿De la miseria, del abandono de siglos, de la ignorancia, o de esa fractura ancestral entre dos mundos que no se conocen ni se entienden?"*[^mvll2] 

[^mvll2]: Vargas Llosa, M. (1983–1990). Contra viento y marea (Vols. 1–3). Seix Barral.

Parecería mentira que un peruano nacido en 1936 tuviera que expresar perplejidad hasta los años ochenta por este tipo de actitudes. El párrafo citado es en sí mismo un metaejemplo: un escritor exitoso y acaudalado, nacido en el Perú, recién palpa con toda su brutal frontalidad el drama nacional central casi cincuenta años después de nacer, y solo a resultas de una masacre y un sangriento conflicto interno.

Don Mario nos dice que los "ciudadanos del común" son más decentes, más racionales y más libres a la hora de votar, y que por ello han caído tantos regímenes autoritarios en América Latina. Mi sospecha es que los regímenes autoritarios —incluidos los peruanos— no fueron defenestrados por la voluntad popular, que por lo demás, cualquiera que fuese, nunca jugó un rol político determinante la mayor parte del tiempo. Fueron extinguiéndose por la falta de viabilidad política y económica, ya que casi siempre se trata de *proxies* o sucedáneos de las clases dominantes, caudillos y militares que fueron marginados cuando las élites llegaron a madurar lo suficiente para poder asumir el poder de modo directo, habiendo educado e integrado a la mayoría de sus pueblos al nivel mínimo necesario para integrarlos a un sistema político representativo, sin correr el riesgo de una anarquía o la debacle de una elección totalmente contraria a sus intereses.

Siempre según don Mario —que parece extrapolar la sociedad británica o norteamericana a nuestros Andes—, las democracias sobreviven porque es ese sentido multitudinario de la justicia lo que predomina por sobre los
intereses de las élites. Me encantaría, en lo personal, vivir en ese país de fábula que describe nuestro Nobel; ver, por una vez, los intereses de la mayoría de la población auténticamente representados y llevados a la práctica. De hecho, al menos en el Perú, las élites se han encargado prontamente de "corregir" o limitar cualquier régimen, democrático o no, que contravenga sus prioridades.

Un poco como respuesta a su coyuntura, y otro poco como manifestación de su ideología liberal, Revel tenía una visión integradora en relación a la actividad terrorista producida en Europa antes del siglo XXI. Aparentemente, creía —contra lo que sospechaban los especialistas en el tema— que los ataques de diversos grupos no eran conatos aislados, sino iniciativas concertadas que buscaban anular a las democracias occidentales. Si bien con el tiempo los servicios de Inteligencia Occidental le dieron la razón, solo fue hasta cierto punto. En efecto, los atentados tenían apoyo logístico y estratégico proveniente de Irán y Libia, aunque con posterioridad a 1990 se convirtieron más que nada en manifestación violenta de movimientos fundamentalistas islámicos. Sin embargo, el objetivo era más modesto que un ataque integral a la democracia: se intentaba "hacer pagar" a Francia y otras potencias occidentales por su apoyo a determinados estados rivales o infligir represalias por el ataque o presencia militar de algunos países europeos en Oriente.
